// <auto-generated />
using System;
using Awhere.Api.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

namespace Awhere.Api.Migrations
{
    [DbContext(typeof(DataService))]
    partial class DataServiceModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Awhere.Api.Models.InfectionPing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Point>("Location")
                        .HasColumnType("geography");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2020, 3, 28, 15, 58, 44, 494, DateTimeKind.Local).AddTicks(6466),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (5.751524 58.853965)"),
                            Severity = 2
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2020, 3, 28, 15, 58, 44, 501, DateTimeKind.Local).AddTicks(1124),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (5.749822 58.854876)"),
                            Severity = 1
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2020, 3, 28, 15, 58, 44, 501, DateTimeKind.Local).AddTicks(2352),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (16.3738 48.2082)"),
                            Severity = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
